version: '3.8'

services:

  postgresql:
    image: postgres
    container_name: ${PROJECT_NAME}-postgresql
    restart: "no"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  django:
    build:
      context: ./
      dockerfile: ./dockerfiles/django/dev/Dockerfile
    container_name: ${PROJECT_NAME}-django
    restart: 'no'
    entrypoint: /django-launcher.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: ${DOMAIN}
      SECRET_KEY: ${SECRET_KEY}
      STATIC_URL: '/static/'
      STATIC_ROOT: 'static'
      MEDIA_URL: '/media/'
      DOMAIN: ${DOMAIN}
      DOMAIN_URL: ${DOMAIN_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    expose:
      - 8000
    depends_on:
      - postgresql

  caddy:
    image: caddy:alpine
    container_name: ${PROJECT_NAME}-caddy
    restart: "no"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - .:/usr/src/app/
    depends_on:
      - django
